### ISSUE TITLE
no sound in ff 58

### ISSUE THREAD

**Issue by smanolache** [Monsterovich/firefox-fuckpa#1]
Hello,

On my machine (debian unstable, x86_64) I have no sound.

I used to do what you did: I've compiled my own with --enable-alsa. It worked well for ff 56 and 57. I compiled ff 58 with --enable-alsa, the compilation succeeded but I have no sound. I don't have the banner saying that I need pulseaudio. Then I've tried again with --enable-alsa --disable-pulseaudio. Still no sound. libxul.so is linked to libasound.so.2.

Then I found your page and took your prebuilt binary. On my machine your build behaves exactly like mine: no banner but no sound either.

Does your build produce sound on your machine? Are there any required dependencies in 58 in addition to the dependencies of 57?

Thanks,
Sorin

**Comment by Monsterovich** [comment]
Indeed. I have no sound on ff 58 too, it seems this is this is a firefox bug.

See errors: https://pastebin.com/NQCdMPcv

**Comment by smanolache** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1430274

**Comment by smanolache** [comment]
I've applied the patch that they published at the link of my previous comment. Now I have sound.

**Comment by alekksander** [comment]
i still have no sound. fresh install. any way do diagnose?

**Comment by Monsterovich** [comment]
>https://github.com/Monsterovich/firefox-fuckpa/blob/master/58.0.2/firefox-58.0.2.en-US.linux-x86_64.tar.bz2

What about this build?

**Comment by alekksander** [comment]
nothing :disappointed:
perhaps some packages missing? what do i need?

**Comment by Monsterovich** [comment]
https://github.com/Monsterovich/firefox-fuckpa/tree/master/58.0.2

I applied the patch to FF, sound works fine now.

**Comment by alekksander** [comment]
~/Applications/fx58 fuckpa/firefox$ ./firefox
[Child 8061, MediaPlayback #1] WARNING: 7ff20e611580 OpenCubeb() failed to init cubeb: file /home/monsterovich/Distfiles/compile/firefox-58.0.2/dom/media/AudioStream.cpp, line 387
[Child 8061, MediaPlayback #1] WARNING: Decoder=7ff20ae60e00 [OnMediaSinkAudioError]: file /home/monsterovich/Distfiles/compile/firefox-58.0.2/dom/media/MediaDecoderStateMachine.cpp, line 3642

**Comment by Monsterovich** [comment]
Hm... sound works fine for me.

**Comment by alekksander** [comment]
@smanolache could You please test Yourself?

**Comment by alekksander** [comment]
turnes out i need dmix to have firefox working, so in
~/.asoundrd i need to have 

`pcm.!default {
	type plug
	slave.pcm "dmixer"
}

pcm.dmixer  {
 	type dmix
 	ipc_key 1024
 	slave {
		pcm "hw:1,0"
		period_time 0
		period_size 2048
		buffer_size 8192
	}
	bindings {
		0 0
		1 1
	}
}

ctl.dmixer {
	type hw
	card 0
}
 
`


however i moved to alsa not to deal with pa and any mixers. seems it's not doable at this point to use pure alsa + firefox

if i may ask, what's in Your .asoundrc?

**Comment by smanolache** [comment]
I have no ~/.asoundrc. Why do you have apulse? If I understand correctly apulse is a tool for pulse audio emulation in alsa. I do not have it and the sound works fine.
[alsa-info.txt](https://github.com/Monsterovich/firefox-fuckpa/files/1800164/alsa-info.txt)
I've attached the output of the "alsa-info" command.

**Comment by alekksander** [comment]
cause i've been trying different approaches. it works without apulse, but also need dmix. it has to be due to my usb dac (objective dac) that:

 'apulse] [error] do_connect_pcm: can't set sample format 14 ("FLOAT_LE") for playback device "default". Error code -22 (Invalid argument)'

but what is format 14? 14bit output from firefox?

**Comment by alekksander** [comment]
please take a look in here:
https://github.com/MrAlex94/Waterfox/issues/464#issuecomment-387261847
